using System;
using System.Collections.Concurrent;
using System.Collections.Generic;
using System.Linq;

namespace MarvelousSoftware.Examples.Samples
{
    public class People
    {
        private static readonly ConcurrentDictionary<int, IQueryable<Person>> _cache 
            = new ConcurrentDictionary<int, IQueryable<Person>>();

        public static IQueryable<Person> Get(int count)
        {
            return _cache.GetOrAdd(count, c =>
            {
                var people = new List<Person>();
                var projects = Project.GetAll().ToArray();

                var userName = "admin";
                var random = new Random();
                while (people.Count < count)
                {
                    people.Add(new Person()
                    {
                        FirstName = FirstNames[random.Next(FirstNames.Length - 1)],
                        LastName = LastNames[random.Next(LastNames.Length - 1)],
                        DateOfBirth = new DateTime(random.Next(1900, DateTime.UtcNow.Year), random.Next(1, 12), random.Next(1, 28)),
                        PlaceOfResidence = Cities[random.Next(0, Cities.Length)],
                        ProjectId = projects[random.Next(0, projects.Length)].Id,
                        DueDate = new DateTime(random.Next(2010, DateTime.UtcNow.AddYears(10).Year), random.Next(1, 12), 1),
                        UserName = userName
                    });
                    userName = null;
                }

                return people.AsQueryable();
            }); 
        }

        public static readonly string[] Cities =
        {
            "Zagreb", "Helsinki", "Prague", "Copenhagen", "Tallinn", "Berlin", "Budapest",
            "Dublin", "Rome", "Warsaw", "Paris", "London", "Monaco", "Amsterdam", "Madrid"
        };

        public static readonly string[] FirstNames =
        {
            "Noah",
            "Liam",
            "Mason",
            "Jacob",
            "William",
            "Ethan",
            "Michael",
            "Alexander",
            "James",
            "Daniel",
            "Elijah",
            "Benjamin",
            "Logan",
            "Aiden",
            "Jayden",
            "Matthew",
            "Jackson",
            "David",
            "Lucas",
            "Joseph",
            "Anthony",
            "Andrew",
            "Samuel",
            "Gabriel",
            "Joshua",
            "John",
            "Carter",
            "Luke",
            "Dylan",
            "Christopher",
            "Isaac",
            "Oliver",
            "Henry",
            "Sebastian",
            "Caleb",
            "Owen",
            "Ryan",
            "Nathan",
            "Wyatt",
            "Hunter",
            "Jack",
            "Christian",
            "Landon",
            "Jonathan",
            "Levi",
            "Jaxon",
            "Julian",
            "Isaiah",
            "Eli",
            "Aaron",
            "Charles",
            "Connor",
            "Cameron",
            "Thomas",
            "Jordan",
            "Jeremiah",
            "Nicholas",
            "Evan",
            "Adrian",
            "Gavin",
            "Robert",
            "Brayden",
            "Grayson",
            "Josiah",
            "Colton",
            "Austin",
            "Angel",
            "Jace",
            "Dominic",
            "Kevin",
            "Brandon",
            "Tyler",
            "Parker",
            "Ayden",
            "Jason",
            "Jose",
            "Ian",
            "Chase",
            "Adam",
            "Hudson",
            "Nolan",
            "Zachary",
            "Easton",
            "Blake",
            "Jaxson",
            "Cooper",
            "Lincoln",
            "Xavier",
            "Bentley",
            "Kayden",
            "Carson",
            "Brody",
            "Asher",
            "Nathaniel",
            "Ryder",
            "Justin",
            "Leo",
            "Juan",
            "Luis",
            "Camden",
            "Emma",
            "Olivia",
            "Sophia",
            "Isabella",
            "Ava",
            "Mia",
            "Emily",
            "Abigail",
            "Madison",
            "Charlotte",
            "Harper",
            "Sofia",
            "Avery",
            "Elizabeth",
            "Amelia",
            "Evelyn",
            "Ella",
            "Chloe",
            "Victoria",
            "Aubrey",
            "Grace",
            "Zoey",
            "Natalie",
            "Addison",
            "Lillian",
            "Brooklyn",
            "Lily",
            "Hannah",
            "Layla",
            "Scarlett",
            "Aria",
            "Zoe",
            "Samantha",
            "Anna",
            "Leah",
            "Audrey",
            "Ariana",
            "Allison",
            "Savannah",
            "Arianna",
            "Camila",
            "Penelope",
            "Gabriella",
            "Claire",
            "Aaliyah",
            "Sadie",
            "Riley",
            "Skylar",
            "Nora",
            "Sarah",
            "Hailey",
            "Kaylee",
            "Paisley",
            "Kennedy",
            "Ellie",
            "Peyton",
            "Annabelle",
            "Caroline",
            "Madelyn",
            "Serenity",
            "Aubree",
            "Lucy",
            "Alexa",
            "Alexis",
            "Nevaeh",
            "Stella",
            "Violet",
            "Genesis",
            "Mackenzie",
            "Bella",
            "Autumn",
            "Mila",
            "Kylie",
            "Maya",
            "Piper",
            "Alyssa",
            "Taylor",
            "Eleanor",
            "Melanie",
            "Naomi",
            "Faith",
            "Eva",
            "Katherine",
            "Lydia",
            "Brianna",
            "Julia",
            "Ashley",
            "Khloe",
            "Madeline",
            "Ruby",
            "Sophie",
            "Alexandra",
            "London",
            "Lauren",
            "Gianna",
            "Isabelle",
            "Alice",
            "Vivian",
            "Hadley",
            "Jasmine"
        };

        public static readonly string[] LastNames =
        {
            "Smith",
            "Johnson",
            "Williams",
            "Jones",
            "Brown",
            "Davis",
            "Miller",
            "Wilson",
            "Moore",
            "Taylor",
            "Anderson",
            "Thomas",
            "Jackson",
            "White",
            "Harris",
            "Martin",
            "Thompson",
            "Garcia",
            "Martinez",
            "Robinson",
            "Clark",
            "Rodriguez",
            "Lewis",
            "Lee",
            "Walker",
            "Hall",
            "Allen",
            "Young",
            "Hernandez",
            "King",
            "Wright",
            "Lopez",
            "Hill",
            "Scott",
            "Green",
            "Adams",
            "Baker",
            "Gonzalez",
            "Nelson",
            "Carter",
            "Mitchell",
            "Perez",
            "Roberts",
            "Turner",
            "Phillips",
            "Campbell",
            "Parker",
            "Evans",
            "Edwards",
            "Collins",
            "Stewart",
            "Sanchez",
            "Morris",
            "Rogers",
            "Reed",
            "Cook",
            "Morgan",
            "Bell",
            "Murphy",
            "Bailey",
            "Rivera",
            "Cooper",
            "Richardson",
            "Cox",
            "Howard",
            "Ward",
            "Torres",
            "Peterson",
            "Gray",
            "Ramirez",
            "James",
            "Watson",
            "Brooks",
            "Kelly",
            "Sanders",
            "Price",
            "Bennett",
            "Wood",
            "Barnes",
            "Ross",
            "Henderson",
            "Coleman",
            "Jenkins",
            "Perry",
            "Powell",
            "Long",
            "Patterson",
            "Hughes",
            "Flores",
            "Washington",
            "Butler",
            "Simmons",
            "Foster",
            "Gonzales",
            "Bryant",
            "Alexander",
            "Russell",
            "Griffin",
            "Diaz",
            "Hayes"
        };
    }
}